import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { getSessionUser, isTeacherOrAdmin } from "@/lib/auth";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

/** GET /api/leaves/settings?teacherId=... */
export async function GET(req: NextRequest) {
    const user = await getSessionUser(req);
    if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const { searchParams } = new URL(req.url);
    const teacherId = searchParams.get("teacherId");

    if (!teacherId) return NextResponse.json({ error: "teacherId required" }, { status: 400 });

    const settings = await prisma.leaveSettings.findUnique({ where: { teacherId } });
    return NextResponse.json(settings);
}

/** POST /api/leaves/settings — create settings */
export async function POST(req: NextRequest) {
    const user = await getSessionUser(req);
    if (!user || !isTeacherOrAdmin(user)) {
        return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    try {
        const body = await req.json();
        const { teacherId, teacherName, weeklyHolidays, joinDate, lastAutoGeneratedDate } = body;

        const settings = await prisma.leaveSettings.upsert({
            where: { teacherId },
            update: { weeklyHolidays: weeklyHolidays || [], joinDate, lastAutoGeneratedDate },
            create: {
                teacherId,
                teacherName,
                weeklyHolidays: weeklyHolidays || [],
                joinDate,
                lastAutoGeneratedDate: lastAutoGeneratedDate || null,
            },
        });

        return NextResponse.json(settings, { status: 201 });
    } catch (error) {
        console.error("[LeaveSettings POST]", error);
        return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
    }
}

/** PATCH /api/leaves/settings */
export async function PATCH(req: NextRequest) {
    const user = await getSessionUser(req);
    if (!user || !isTeacherOrAdmin(user)) {
        return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    try {
        const body = await req.json();
        const { teacherId, ...data } = body;
        const settings = await prisma.leaveSettings.update({ where: { teacherId }, data });
        return NextResponse.json(settings);
    } catch (error) {
        console.error("[LeaveSettings PATCH]", error);
        return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
    }
}
