import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

export function middleware(request: NextRequest) {
    // Read the session cookie generated by our AuthContext
    const session = request.cookies.get('__session')?.value;

    const isStudentPath = request.nextUrl.pathname.startsWith('/student-dashboard');

    // ── Guard 1: cookie missing entirely ─────────────────
    if (!session) {
        if (isStudentPath) {
            return NextResponse.redirect(new URL('/student-login', request.url));
        }
        return NextResponse.redirect(new URL('/login', request.url));
    }

    // ── Guard 2: obviously fake / truncated token ─────────
    // A real Firebase ID token is a JWT with 3 base64 segments and is
    // always well over 100 characters. Anything shorter is suspicious.
    // WARNING: This is a basic heuristic ONLY. A proper production
    // implementation MUST verify the JWT signature using firebase-admin
    // (e.g. in a Cloud Function or a secure server-side route), because
    // a forged token with sufficient length passes this check.
    const MIN_VALID_SESSION_LENGTH = 20;
    if (session.length < MIN_VALID_SESSION_LENGTH) {
        if (isStudentPath) {
            return NextResponse.redirect(new URL('/student-login', request.url));
        }
        return NextResponse.redirect(new URL('/login', request.url));
    }

    // Pass through — client-side AuthContext will do the full profile check
    return NextResponse.next();
}

// Ensure the middleware is only invoked for protected routes
export const config = {
    matcher: ['/dashboard/:path*', '/student-dashboard/:path*'],
};
