import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

export function middleware(request: NextRequest) {
    // Read the session cookie generated by our AuthContext
    const session = request.cookies.get('__session')?.value;

    if (!session) {
        // Redirect logic for unauthenticated users
        if (request.nextUrl.pathname.startsWith('/student-dashboard')) {
            return NextResponse.redirect(new URL('/student-login', request.url));
        }
        return NextResponse.redirect(new URL('/login', request.url));
    }

    // Pass through if authenticated
    return NextResponse.next();
}

// Ensure the middleware is only invoked for protected routes
export const config = {
    matcher: ['/dashboard/:path*', '/student-dashboard/:path*'],
};
