// ============================================================
// leaveService — All Firestore calls replaced with API calls
// ============================================================

export interface Leave {
    id?: string;
    teacherId: string;
    teacherName: string;
    startDate: string;
    endDate: string;
    days: number;
    type: "Casual" | "Sick" | "WeeklyHoliday" | "Other";
    reason?: string;
    monthYear: string;
}

export interface LeaveSettings {
    id?: string;
    teacherId: string;
    teacherName: string;
    weeklyHolidays: string[];
    joinDate: string;
    lastAutoGeneratedDate?: string;
}

// Alias for backward compatibility
export type TeacherLeaveSettings = LeaveSettings;


export const getLeavesByTeacher = async (teacherId: string): Promise<Leave[]> => {
    const res = await fetch(`/api/leaves?teacherId=${encodeURIComponent(teacherId)}`, { cache: "no-store" });
    if (!res.ok) return [];
    return res.json();
};

export const getLeavesByMonth = async (teacherId: string, monthYear: string): Promise<Leave[]> => {
    const res = await fetch(`/api/leaves?teacherId=${encodeURIComponent(teacherId)}&monthYear=${encodeURIComponent(monthYear)}`, { cache: "no-store" });
    if (!res.ok) return [];
    return res.json();
};

export const addLeave = async (leave: Omit<Leave, "id">): Promise<string> => {
    const res = await fetch("/api/leaves", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(leave),
    });
    const data = await res.json();
    if (!res.ok) throw new Error(data.error || "Failed to add leave.");
    return data.id;
};

export const deleteLeave = async (id: string): Promise<void> => {
    const res = await fetch(`/api/leaves?id=${encodeURIComponent(id)}`, { method: "DELETE" });
    if (!res.ok) throw new Error("Failed to delete leave.");
};

export const getLeaveSettings = async (teacherId: string): Promise<LeaveSettings | null> => {
    const res = await fetch(`/api/leaves/settings?teacherId=${encodeURIComponent(teacherId)}`, { cache: "no-store" });
    if (!res.ok) return null;
    return res.json();
};

export const saveLeaveSettings = async (settings: Omit<LeaveSettings, "id">): Promise<void> => {
    const res = await fetch("/api/leaves/settings", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(settings),
    });
    if (!res.ok) throw new Error("Failed to save leave settings.");
};

export const autoGenerateWeeklyLeaves = async (teacherId: string): Promise<{ generated: number }> => {
    const res = await fetch("/api/leaves/auto-generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ teacherId }),
    });
    const data = await res.json();
    if (!res.ok) throw new Error(data.error || "Failed to auto-generate weekly leaves.");
    return data;
};

// ─── Backward-compat aliases ─────────────────────────────────

/** Alias for autoGenerateWeeklyLeaves */
export const syncAutoWeeklyLeaves = autoGenerateWeeklyLeaves;

/** Update a single leave record */
export const updateLeave = async (id: string, data: Partial<Omit<Leave, "id">>): Promise<void> => {
    const res = await fetch("/api/leaves", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id, ...data }),
    });
    if (!res.ok) throw new Error("Failed to update leave.");
};

/** Remove duplicate weekly leaves for a teacher */
export const cleanDuplicateWeeklyLeaves = async (teacherId: string): Promise<number> => {
    const res = await fetch("/api/leaves/clean-duplicates", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ teacherId }),
    });
    if (!res.ok) throw new Error("Failed to clean duplicate leaves.");
    const data = await res.json();
    return data.deletedCount || data.count || data.deleted || 1;
};

