import { collection, doc, getDocs, getDoc, setDoc, addDoc, updateDoc, deleteDoc, query, where, serverTimestamp } from "firebase/firestore";
import { db } from "@/lib/firebase";
import { Teacher } from "./teacherService";

// Collection names
const LEAVES_COL = "leaves";
const LEAVE_SETTINGS_COL = "leave_settings";

export type LeaveType = "Casual" | "Sick" | "Weekly Holiday" | "Other";

export interface Leave {
    id?: string;
    teacherId: string;
    teacherName: string;
    startDate: string; // YYYY-MM-DD
    endDate: string; // YYYY-MM-DD
    days: number;
    type: LeaveType;
    reason?: string;
    monthYear: string; // YYYY-MM
    createdAt?: any;
}

export interface TeacherLeaveSettings {
    teacherId: string;
    teacherName: string;
    weeklyHolidays: number[]; // 0=Sun, 1=Mon, ..., 6=Sat
    joinDate: string; // YYYY-MM-DD
    lastAutoGeneratedDate?: string; // YYYY-MM-DD
}

// ---------------------- LEAVE SETTINGS ----------------------

export const getLeaveSettings = async (teacherId: string): Promise<TeacherLeaveSettings | null> => {
    try {
        const docRef = doc(db, LEAVE_SETTINGS_COL, teacherId);
        const docSnap = await getDoc(docRef);
        if (docSnap.exists()) {
            return {
                teacherId: docSnap.id,
                ...docSnap.data()
            } as TeacherLeaveSettings;
        }
        return null;
    } catch (error) {
        console.error("Error getting leave settings:", error);
        return null;
    }
};

export const saveLeaveSettings = async (teacherId: string, data: Partial<TeacherLeaveSettings>): Promise<void> => {
    try {
        const docRef = doc(db, LEAVE_SETTINGS_COL, teacherId);
        await setDoc(docRef, { ...data }, { merge: true });
    } catch (error) {
        console.error("Error saving leave settings:", error);
        throw error;
    }
};

// ---------------------- LEAVES MANAGEMENT ----------------------

export const getLeavesByTeacher = async (teacherId: string): Promise<Leave[]> => {
    try {
        // Use only `where` filter to avoid composite index requirement; sort client-side
        const q = query(
            collection(db, LEAVES_COL),
            where("teacherId", "==", teacherId)
        );
        const snapshot = await getDocs(q);
        const leaves = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }) as Leave);
        // Sort descending by startDate on the client
        return leaves.sort((a, b) => b.startDate.localeCompare(a.startDate));
    } catch (error) {
        console.error("Error getting leaves:", error);
        return [];
    }
};

export const getAllLeaves = async (): Promise<Leave[]> => {
    try {
        const snapshot = await getDocs(collection(db, LEAVES_COL));
        const leaves = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }) as Leave);
        return leaves.sort((a, b) => b.startDate.localeCompare(a.startDate));
    } catch (error) {
        console.error("Error getting all leaves:", error);
        return [];
    }
};

export const addLeave = async (data: Omit<Leave, "id" | "createdAt">): Promise<string> => {
    try {
        const docRef = await addDoc(collection(db, LEAVES_COL), {
            ...data,
            createdAt: serverTimestamp()
        });
        return docRef.id;
    } catch (error) {
        console.error("Error adding leave:", error);
        throw error;
    }
};

export const updateLeave = async (id: string, data: Partial<Leave>): Promise<void> => {
    try {
        const docRef = doc(db, LEAVES_COL, id);
        await updateDoc(docRef, { ...data, updatedAt: serverTimestamp() });
    } catch (error) {
        console.error("Error updating leave:", error);
        throw error;
    }
};

export const deleteLeave = async (id: string): Promise<void> => {
    try {
        await deleteDoc(doc(db, LEAVES_COL, id));
    } catch (error) {
        console.error("Error deleting leave:", error);
        throw error;
    }
};

// ---------------------- AUTO CALCULATION ----------------------

/**
 * Calculates and inserts missing "Weekly Holiday" leaves up to the current date.
 * Deduplication: fetches all existing weekly holiday dates for the teacher first,
 * so concurrent calls never insert the same date twice.
 */
export const syncAutoWeeklyLeaves = async (teacher: Teacher): Promise<void> => {
    try {
        const settings = await getLeaveSettings(teacher.id);
        if (!settings || !settings.weeklyHolidays || settings.weeklyHolidays.length === 0) {
            return; // No weekly holidays configured
        }

        // --- Step 1: Fetch all existing "Weekly Holiday" dates for this teacher ---
        const existingQ = query(
            collection(db, LEAVES_COL),
            where("teacherId", "==", teacher.id),
            where("type", "==", "Weekly Holiday")
        );
        const existingSnap = await getDocs(existingQ);
        // Build a Set of existing startDates for O(1) lookup
        const existingDates = new Set<string>(
            existingSnap.docs.map(d => (d.data() as Leave).startDate)
        );

        // --- Step 2: Determine iteration start date ---
        let currentIterDate: Date;
        if (settings.lastAutoGeneratedDate) {
            currentIterDate = new Date(settings.lastAutoGeneratedDate + "T00:00:00");
            currentIterDate.setDate(currentIterDate.getDate() + 1);
        } else if (settings.joinDate) {
            currentIterDate = new Date(settings.joinDate + "T00:00:00");
        } else {
            currentIterDate = new Date(new Date().getFullYear(), 0, 1);
        }

        const today = new Date();
        today.setHours(0, 0, 0, 0);

        let lastGeneratedDateStr = settings.lastAutoGeneratedDate;
        let generatedAny = false;

        // --- Step 3: Walk day by day, skip already-existing dates ---
        while (currentIterDate <= today) {
            const dayOfWeek = currentIterDate.getDay();
            if (settings.weeklyHolidays.includes(dayOfWeek)) {
                const yyyy = currentIterDate.getFullYear();
                const mm = String(currentIterDate.getMonth() + 1).padStart(2, "0");
                const dd = String(currentIterDate.getDate()).padStart(2, "0");
                const dateStr = yyyy + "-" + mm + "-" + dd;
                const monthYear = yyyy + "-" + mm;

                // ✅ Only insert if not already present
                if (!existingDates.has(dateStr)) {
                    await addLeave({
                        teacherId: teacher.id,
                        teacherName: teacher.name,
                        startDate: dateStr,
                        endDate: dateStr,
                        days: 1,
                        type: "Weekly Holiday",
                        reason: "Automated weekly off",
                        monthYear: monthYear,
                    });
                    existingDates.add(dateStr); // prevent re-insert within same run
                }

                lastGeneratedDateStr = dateStr;
                generatedAny = true;
            }
            currentIterDate.setDate(currentIterDate.getDate() + 1);
        }

        if (generatedAny) {
            await saveLeaveSettings(teacher.id, {
                lastAutoGeneratedDate: lastGeneratedDateStr,
            });
        }

    } catch (error) {
        console.error("Error syncing auto weekly leaves:", error);
    }
};

/**
 * Removes duplicate "Weekly Holiday" records (same teacherId + startDate).
 * Keeps one document per date and deletes the rest.
 * Returns number of deleted duplicates.
 */
export const cleanDuplicateWeeklyLeaves = async (teacherId: string): Promise<number> => {
    try {
        const q = query(
            collection(db, LEAVES_COL),
            where("teacherId", "==", teacherId),
            where("type", "==", "Weekly Holiday")
        );
        const snap = await getDocs(q);

        // Group by startDate
        const byDate: Record<string, string[]> = {}; // date -> [docId, ...]
        snap.docs.forEach(d => {
            const date = (d.data() as Leave).startDate;
            if (!byDate[date]) byDate[date] = [];
            byDate[date].push(d.id);
        });

        let deleted = 0;
        for (const [, ids] of Object.entries(byDate)) {
            if (ids.length > 1) {
                // Keep the first, delete the rest
                const toDelete = ids.slice(1);
                for (const id of toDelete) {
                    await deleteDoc(doc(db, LEAVES_COL, id));
                    deleted++;
                }
            }
        }
        return deleted;
    } catch (error) {
        console.error("Error cleaning duplicate weekly leaves:", error);
        return 0;
    }
};

