import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { getSessionUser, isAdmin } from "@/lib/auth";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

/**
 * POST /api/leaves/auto-generate
 * Auto-generates WeeklyHoliday leave entries for a teacher
 * based on their LeaveSettings.weeklyHolidays configuration.
 */
export async function POST(req: NextRequest) {
    const user = await getSessionUser(req);
    if (!user || !isAdmin(user)) {
        return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    try {
        const body = await req.json();
        const { teacherId } = body;
        // Default to current month if not provided
        const now = new Date();
        const monthYear = body.monthYear || `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;

        if (!teacherId) {
            return NextResponse.json({ error: "teacherId required" }, { status: 400 });
        }

        const settings = await prisma.leaveSettings.findUnique({ where: { teacherId } });
        if (!settings) {
            return NextResponse.json({ error: "No leave settings found for this teacher" }, { status: 404 });
        }

        const weeklyHolidays = (settings.weeklyHolidays as string[]) || [];
        if (weeklyHolidays.length === 0) {
            return NextResponse.json({ generated: 0, message: "No weekly holidays configured" });
        }

        const [year, month] = monthYear.split("-").map(Number);
        const daysInMonth = new Date(year, month, 0).getDate();
        const dayNames = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

        const created: string[] = [];

        for (let day = 1; day <= daysInMonth; day++) {
            const date = new Date(year, month - 1, day);
            const dayName = dayNames[date.getDay()];

            if (!weeklyHolidays.includes(dayName)) continue;

            const dateStr = `${year}-${String(month).padStart(2, "0")}-${String(day).padStart(2, "0")}`;

            const existing = await prisma.leave.findFirst({
                where: { teacherId, startDate: dateStr, type: "WeeklyHoliday" },
            });

            if (existing) continue;

            const leave = await prisma.leave.create({
                data: {
                    teacherId,
                    teacherName: settings.teacherName,
                    startDate: dateStr,
                    endDate: dateStr,
                    days: 1,
                    type: "WeeklyHoliday",
                    reason: "Auto-generated weekly holiday",
                    monthYear,
                },
            });

            created.push(leave.id);
        }

        await prisma.leaveSettings.update({
            where: { teacherId },
            data: { lastAutoGeneratedDate: monthYear },
        });

        return NextResponse.json({ generated: created.length, ids: created });
    } catch (error) {
        console.error("[Leaves AutoGenerate]", error);
        return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
    }
}
