import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { getSessionUser, isAdmin } from "@/lib/auth";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

const DAY_NAMES = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

function toMonthYear(date: Date): string {
    return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`;
}

function addMonths(monthYear: string, n: number): string {
    const [y, m] = monthYear.split("-").map(Number);
    const d = new Date(y, m - 1 + n, 1);
    return toMonthYear(d);
}

function monthsRange(from: string, to: string): string[] {
    const months: string[] = [];
    let cur = from;
    while (cur <= to) {
        months.push(cur);
        cur = addMonths(cur, 1);
    }
    return months;
}

async function generateForMonth(
    teacherId: string,
    teacherName: string,
    weeklyHolidays: string[],
    monthYear: string,
    today: string,
): Promise<number> {
    const [year, month] = monthYear.split("-").map(Number);
    const daysInMonth = new Date(year, month, 0).getDate();
    let created = 0;

    for (let day = 1; day <= daysInMonth; day++) {
        const dateStr = `${year}-${String(month).padStart(2, "0")}-${String(day).padStart(2, "0")}`;
        // Don't generate future dates
        if (dateStr > today) break;

        const date = new Date(year, month - 1, day);
        const dayName = DAY_NAMES[date.getDay()];
        if (!weeklyHolidays.includes(dayName)) continue;

        const existing = await prisma.leave.findFirst({
            where: { teacherId, startDate: dateStr, type: "WeeklyHoliday" },
        });
        if (existing) continue;

        await prisma.leave.create({
            data: {
                teacherId,
                teacherName,
                startDate: dateStr,
                endDate: dateStr,
                days: 1,
                type: "WeeklyHoliday",
                reason: "Auto-generated weekly holiday",
                monthYear,
            },
        });
        created++;
    }
    return created;
}

/**
 * POST /api/leaves/auto-generate
 * Generates WeeklyHoliday entries from a start month to today.
 * - If monthYear provided: only that month
 * - If not provided: generates ALL months from max(joinDate, "2026-01") to today (backfill + current)
 */
export async function POST(req: NextRequest) {
    const user = await getSessionUser(req);
    if (!user || !isAdmin(user)) {
        return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    try {
        const body = await req.json();
        const { teacherId, monthYear: specificMonth } = body;

        if (!teacherId) {
            return NextResponse.json({ error: "teacherId required" }, { status: 400 });
        }

        const settings = await prisma.leaveSettings.findUnique({ where: { teacherId } });
        if (!settings) {
            return NextResponse.json({ error: "No leave settings found for this teacher" }, { status: 404 });
        }

        const weeklyHolidays = (settings.weeklyHolidays as string[]) || [];
        if (weeklyHolidays.length === 0) {
            return NextResponse.json({ generated: 0, message: "No weekly holidays configured" });
        }

        const now = new Date();
        const todayStr = now.toISOString().slice(0, 10);
        const currentMonth = toMonthYear(now);

        let totalGenerated = 0;

        if (specificMonth) {
            // Generate only for the specified month
            totalGenerated = await generateForMonth(
                teacherId, settings.teacherName, weeklyHolidays, specificMonth, todayStr
            );
            await prisma.leaveSettings.update({
                where: { teacherId },
                data: { lastAutoGeneratedDate: specificMonth },
            });
        } else {
            // Determine start: max(joinDate month, "2026-01")
            let startMonth = "2026-01";
            if (settings.joinDate && settings.joinDate >= "2026-01") {
                startMonth = settings.joinDate.slice(0, 7); // "YYYY-MM"
            }

            // Generate all months from startMonth to currentMonth
            const months = monthsRange(startMonth, currentMonth);
            for (const month of months) {
                const count = await generateForMonth(
                    teacherId, settings.teacherName, weeklyHolidays, month, todayStr
                );
                totalGenerated += count;
            }

            await prisma.leaveSettings.update({
                where: { teacherId },
                data: { lastAutoGeneratedDate: currentMonth },
            });
        }

        return NextResponse.json({ generated: totalGenerated });
    } catch (error) {
        console.error("[Leaves AutoGenerate]", error);
        return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
    }
}
