import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { getSessionUser, isAdmin } from "@/lib/auth";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

const DAY_NAMES = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

function toMonthYear(date: Date): string {
    return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`;
}

function addMonths(monthYear: string, n: number): string {
    const [y, m] = monthYear.split("-").map(Number);
    return toMonthYear(new Date(y, m - 1 + n, 1));
}

function monthsRange(from: string, to: string): string[] {
    const months: string[] = [];
    let cur = from;
    while (cur <= to) {
        months.push(cur);
        cur = addMonths(cur, 1);
    }
    return months;
}

/**
 * Normalises a weeklyHolidays entry to a day index (0=Sun … 6=Sat).
 * Accepts both day names ("Friday") and numeric strings/numbers ("5").
 */
function toDayIndex(v: string | number): number {
    const n = Number(v);
    if (!isNaN(n) && String(v).trim() !== "") return n;
    return DAY_NAMES.indexOf(String(v));
}

async function generateForMonth(
    teacherId: string,
    teacherName: string,
    weeklyHolidayIndices: number[],
    monthYear: string,
    today: string,
): Promise<number> {
    const [year, month] = monthYear.split("-").map(Number);
    const daysInMonth = new Date(year, month, 0).getDate();
    let created = 0;

    for (let day = 1; day <= daysInMonth; day++) {
        const dateStr = `${year}-${String(month).padStart(2, "0")}-${String(day).padStart(2, "0")}`;
        if (dateStr > today) break;

        const dayIndex = new Date(year, month - 1, day).getDay();
        if (!weeklyHolidayIndices.includes(dayIndex)) continue;

        // Skip if any entry already exists for this date (WeeklyHoliday or auto-generated Other)
        const existing = await prisma.leave.findFirst({
            where: {
                teacherId,
                startDate: dateStr,
                OR: [
                    { type: "WeeklyHoliday" },
                    { reason: "Auto-generated weekly holiday" },
                ],
            },
        });
        if (existing) continue;

        await prisma.leave.create({
            data: {
                teacherId,
                teacherName,
                startDate: dateStr,
                endDate: dateStr,
                days: 1,
                type: "WeeklyHoliday",
                reason: "Auto-generated weekly holiday",
                monthYear,
            },
        });
        created++;
    }
    return created;
}

/**
 * POST /api/leaves/auto-generate
 * Generates WeeklyHoliday entries from a start month to today.
 * - If monthYear provided: only that month
 * - If not: generates ALL months from max(joinDate, "2026-01") to today
 */
export async function POST(req: NextRequest) {
    const user = await getSessionUser(req);
    if (!user || !isAdmin(user)) {
        return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    try {
        const body = await req.json();
        const { teacherId, monthYear: specificMonth } = body;

        if (!teacherId) {
            return NextResponse.json({ error: "teacherId required" }, { status: 400 });
        }

        const settings = await prisma.leaveSettings.findUnique({ where: { teacherId } });
        if (!settings) {
            return NextResponse.json({ generated: 0, message: "No leave settings found" });
        }

        const rawHolidays = (settings.weeklyHolidays as (string | number)[]) || [];
        const weeklyHolidayIndices = rawHolidays
            .map(toDayIndex)
            .filter(i => i >= 0 && i <= 6);

        if (weeklyHolidayIndices.length === 0) {
            return NextResponse.json({ generated: 0, message: "No weekly holidays configured" });
        }

        const now = new Date();
        const todayStr = now.toISOString().slice(0, 10);
        const currentMonth = toMonthYear(now);
        let totalGenerated = 0;

        if (specificMonth) {
            totalGenerated = await generateForMonth(
                teacherId, settings.teacherName, weeklyHolidayIndices, specificMonth, todayStr
            );
            await prisma.leaveSettings.update({
                where: { teacherId },
                data: { lastAutoGeneratedDate: specificMonth },
            });
        } else {
            let startMonth = "2026-01";
            if (settings.joinDate && settings.joinDate >= "2026-01") {
                startMonth = settings.joinDate.slice(0, 7);
            }
            const months = monthsRange(startMonth, currentMonth);
            for (const month of months) {
                totalGenerated += await generateForMonth(
                    teacherId, settings.teacherName, weeklyHolidayIndices, month, todayStr
                );
            }
            await prisma.leaveSettings.update({
                where: { teacherId },
                data: { lastAutoGeneratedDate: currentMonth },
            });
        }

        return NextResponse.json({ generated: totalGenerated });
    } catch (error) {
        console.error("[Leaves AutoGenerate]", error);
        return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
    }
}
